### ISSUE TITLE
Cannot delete members of Type Dialogue

### ISSUE THREAD

**Issue by ninetailsdev** [YodasMyDad/Dialogue#46]
I've created over 100 hundred different dialogue members in order to test the forum as much as I can. When I tried to delete them I get an error telling me to check the log file where i got the following:

```
  2015-01-19 09:21:19,090 [5] ERROR System.Web.IHtmlString - [Thread 15] Dialogue Package: Error trying to delete Dialogue member
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Collections.ObjectModel.KeyedCollection`2.get_Item(TKey key)
   at Dialogue.Logic.Services.MemberService.RefreshMemberPosts(Member member, Int32 amount)
   at Dialogue.Logic.Services.PostService.SyncMembersPostCount(List`1 members)
   at Dialogue.Logic.Services.PostService.Delete(Post post)
   at Dialogue.Logic.Services.MemberService.DeleteAllAssociatedMemberInfo(Int32 userId, UnitOfWork unitOfWork)

2015-01-19 09:21:19,095 [5] ERROR System.Web.IHtmlString - [Thread 24] Dialogue Package:           Error trying to delete Dialogue member
 System.Collections.Generic.KeyNotFoundException: The given key was not present in the    dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Collections.ObjectModel.KeyedCollection`2.get_Item(TKey key)
   at Dialogue.Logic.Services.MemberService.RefreshMemberPosts(Member member, Int32 amount)
   at Dialogue.Logic.Services.PostService.SyncMembersPostCount(List`1 members)
   at Dialogue.Logic.Services.PostService.Delete(Post post)
   at Dialogue.Logic.Services.MemberService.DeleteAllAssociatedMemberInfo(Int32 userId, UnitOfWork unitOfWork)


2015-01-19 09:21:19,110 [5] WARN  System.Web.IHtmlString - [Thread 15] Dialogue Package: There was an error attemping to delete member barry scott and all of their associated data (Posts, Topics etc...)
2015-01-19 09:21:19,131 [5] WARN  System.Web.IHtmlString - [Thread 24] Dialogue Package:    There was an error attemping to delete member bryanredban and all of their associated data (Posts, Topics etc...)
2015-01-19 09:22:07,960 [5] ERROR Umbraco.Web.Scheduling.ScheduledPublishing - [Thread 8] An error occurred with the scheduled publishing
```

System.Net.WebException: The remote server returned an error: (404) Not Found.
       at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
       at System.Net.WebClient.UploadString(Uri address, String method, String data)
       at Umbraco.Web.Scheduling.ScheduledPublishing.Run()     

I can delete threads and forum sections, just not memebers. I've tried complete uninstalling dialogue and reinstalling and I get the same issue. I've also created a fresh site and installed there with nothing but dialogue in it thinking maybe it was some of my code, but the issue also persisted on there as well.

**Comment by leen3o** [comment]
I'm knee deep in client work at the mo. Once I've finished it I'll have a look into it further.

**Comment by ninetailsdev** [comment]
I changed the avatar to a text box and I'm now able to delete dialogue members. 

I've got a feeling that it may have something to do with there being no avatar image to delete and its just not liking it.

**Comment by OptimisticCoder** [comment]
Reproduced this issue with a standard member, as it was failing because "postCount" property was missing on non-Dialogue member types.
Added a check to see if it exists first, so https://github.com/YodasMyDad/Dialogue/pull/83 should resolve it.

**Comment by YodasMyDad** [comment]
Fixed
