### ISSUE TITLE
Using Latest Topics summary on Umbraco site pages

### ISSUE THREAD

**Issue by Prospero100** [YodasMyDad/Dialogue#54]
Hi Lee,
I'm up and running with Dialogue now. It's great. I've moved the forum underneath the website homepage and generally fitted into my site. I've used a partial view to a call to the DialogueTopicSurfaceController to show the latest topics on my website home page. Using  
@Html.Action("LatestTopics", "DialogueTopicSurface")

This displays great on the home page and pulls though the latest forum posts. If I call the exact same partial view from any other page than the website home page I get the error:

Object reference not set to an instance of an object.
   at Dialogue.Logic.Controllers.DialogueTopicSurfaceController.LatestTopics(Nullable`1 p)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)

Which looks like a linq error in retrieving the latest posts. Any ideas why this would be the case on level 1 pages, but not on the site root page?

**Comment by YodasMyDad** [comment]
Can't replicate
